export * from './About';
export * from './Cart';
export * from './Collections';
export * from './Contact';
export * from './Home';
export * from './Login';
export * from './Orders';
export * from './PlaceOrder';
export * from './Product';